### ISSUE TITLE
PHP version?

### ISSUE THREAD

**Issue by damascene** [jeton-tech/jeton-lib#2]
This library solves a very important issue and I believe it will help adoption a lot. I was searching of the possibility to have PHP clone of it so it could be used by many PHP developers.

Is there any chance of creating a Jeton PHP library?
It could depend on https://github.com/btccom/bitwasp-bitcoin-bch-addon libraries. Your input is so appreciated.

**Comment by vinarmani** [comment]
There are no plans to do this as a PHP library at the moment.
